// flow-typed signature: a89719b41c882992aca185dba5ab82dd
// flow-typed version: <<STUB>>/fzkes_v^0.15.0/flow_v0.113.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fzkes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fzkes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fzkes/src/chai' {
  declare module.exports: any;
}

declare module 'fzkes/src/fake' {
  declare module.exports: any;
}

declare module 'fzkes/src/is-fake' {
  declare module.exports: any;
}

declare module 'fzkes/src/scope' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fzkes/index' {
  declare module.exports: $Exports<'fzkes'>;
}
declare module 'fzkes/index.js' {
  declare module.exports: $Exports<'fzkes'>;
}
declare module 'fzkes/src/chai.js' {
  declare module.exports: $Exports<'fzkes/src/chai'>;
}
declare module 'fzkes/src/fake.js' {
  declare module.exports: $Exports<'fzkes/src/fake'>;
}
declare module 'fzkes/src/is-fake.js' {
  declare module.exports: $Exports<'fzkes/src/is-fake'>;
}
declare module 'fzkes/src/scope.js' {
  declare module.exports: $Exports<'fzkes/src/scope'>;
}
